import path from "path"
import fs from "fs"

import { zodToTs, createTypeAlias, printNode } from "zod-to-ts"
import { $ } from "execa"

import schemas from "../src/schemas"

const { typeDefinitions } = schemas

async function main() {
	const types: string[] = [
		"// This file is automatically generated by running `npm run generate-types`\n// Do not edit it directly.",
	]

	for (const { schema, identifier } of typeDefinitions) {
		try {
			// Skip type generation for complex schemas to avoid deep instantiation
			if (identifier === 'ProviderSettings' || identifier === 'GlobalSettings' || identifier === 'RooCodeSettings') {
				console.log(`Skipping type generation for complex schema: ${identifier}`)
				types.push(`export type ${identifier} = any`)
			} else {
				// Use type assertion to avoid deep type processing
				const schemaObj = zodToTs(schema as any, identifier) as any
				if (schemaObj?.node) {
					types.push(printNode(createTypeAlias(schemaObj.node, identifier)))
				}
				types.push(`export type { ${identifier} }`)
			}
		} catch (error) {
			console.warn(`Failed to generate types for ${identifier}: ${error}`)
			// Fallback to simple type export with correct syntax
			types.push(`export type ${identifier} = any`)
		}
	}

	fs.writeFileSync("src/exports/types.ts", types.join("\n\n"))

	await $`npx tsup src/exports/interface.ts --dts -d out`
	fs.copyFileSync("out/interface.d.ts", "src/exports/roo-code.d.ts")

	await $`npx prettier --write src/exports/types.ts src/exports/roo-code.d.ts`

	if (fs.existsSync(path.join("..", "Roo-Code-Types"))) {
		fs.copyFileSync("out/interface.js", path.join("..", "Roo-Code-Types", "src", "index.js"))
		fs.copyFileSync("out/interface.d.ts", path.join("..", "Roo-Code-Types", "src", "index.d.ts"))
	}
}

main()
